spring:
  profiles:
    active: ${mcp.transport:default}
  application:
    name: openapi-diff-mcp-server
  ai:
    mcp:
      server:
        name: openapi-diff-mcp-server
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        sse-message-endpoint: /mcp/messages