spring:
  application:
    name: openapi-diff-mcp-server
  main:
    # NOTE: You must disable the banner and the console logging
    # to allow the STDIO transport to work !!!
    banner-mode: off
  ai:
    mcp:
      server:
        name: openapi-diff-mcp-server
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        sse-message-endpoint: /mcp/messages